	BPL	#BANK#_#MAGIC#_SmallerThan128
	AND	#%01111111	
	JMP	#BANK#_#MAGIC#_DECRLoop_Before
#BANK#_#MAGIC#_SmallerThan128
	STA	#TEMPVAR#
	LDA	#128
	SEC
	SBC	#TEMPVAR#
#BANK#_#MAGIC#_DECRLoop_Before
	LSR
	CLC
#BANK#_#MAGIC#_DECRLoop
	STA	#TEMPVAR#
	DEX
	CPX	#0
	BNE	#BANK#_#MAGIC#_DECRLoop_END
	LSR	
	JMP	#BANK#_#MAGIC#_DECRLoop
#BANK#_#MAGIC#_DECRLoop_END
	TAY
	BMI	#BANK#_#MAGIC#_LargerThan127
	LDA	#128
	SEC
	SBC	#TEMPVAR#
	JMP	#BANK#_#MAGIC#_Finished
#BANK#_#MAGIC#_LargerThan127
	LDA	#128	
 	CLC
	ADC	#TEMPVAR#
#BANK#_#MAGIC#_Finished
